const jokes = [
  "Did you hear about the invisible man who went to the doctor? He’s still waiting to be seen.",
  "My best friend thinks I'm too competitive. I told her I already knew that.",
  "Why did the lady put lipstick on her forehead? She was trying to makeup her mind.",
  "Why don't zombies eat clowns? Because they taste funny.",
  "Why do dolphins sing off-key? Because you can't tuna fish.",
  "Why shouldn't you tell pigs your secrets? Because they always squeal.",
  "What do you get from a selfish cow? Spoiled milk.",
  "Why did the teacher go to the eye doctor? She couldn't control her pupils.",
  "My boss told me to have a good day. So, I didn’t go to work.",
  "Why do cemeteries have fences? Because everyone's dying to get in.",
  "Why did the cat get arrested? He was caught littering.",
  "Didja hear about the computer that went to the doctor? It had a virus.",
  "Why don't sailors wear red or blue? They're afraid they'll up marooned.",
  "Why did the sand get offended? Because the sea weed.",
  "They filmed a documentary about constipation once. But it never came out.",
  "Why did the owl quit school? He wanted time to figure out who he was.",
  "Why did the soldier go AWOL? It's a private matter.",
  "Why should you take advice from a porcupine? They have a lot of good points.",
  "What kind of bagels do jets like? Plain.",
  "Where do spiders buy their clothes? On the web.",
  "Why do libraries have elevators? Because they have a lot of stories.",
  "Why is it so hard to drive in a screw? Because it doesn't have a steering wheel.",
  "Why didn't the skeleton cross the road? Not enough guts.",
  "A husband says to his wife, “I’m going to make you the happiest woman in the world.” The wife responds with, “I'll miss you.”",
  "What do you call a lobster that won't share? Shell-fish.",
  "What did the duck say when the waiter brought the check? “Put it on my bill.”",
  "What did the tree say when spring arrived? “What a re-leaf!”",
  "Why was six nervous? Because seven eight nine.",
  "What do evil hens lay? Deviled eggs.",
  "I once met a giant. I didn't know what to say, so I used big words.",
  "What do bees use to fix their hair? Honeycombs.",
  "Can February March? No, but April May.",
  "I had a conversation with a dolphin once. It felt like we really clicked.",
  "How can you tell if a plant is good at math? It has square roots.",
  "How do penguins fix broken dishes? With igloo.",
  "I'd tell you a pizza joke, but it's a bit too cheesy.",
  "Two kittens had an argument. It ended in a cat-astrophe.",
  "What do you call a rude cow? Beef jerky.",
  "How do trains eat? They choo-choo.",
  "What do you call a moose with no name? Anony-moose.",
  "Where do cows go on dates? To the moo-vies.",
  "What do you call a duck that likes the Fourth of July? A fire-quacker.",
  "Where do birds go when they eat dinner out? Someplace cheep.",
  "A horse goes into a restaurant. The host says, “Hey!” The horse replies, “You read my mind.”",
  "What month of the year has 28 days? All of them.",
  "What did the envelope say to the stamp? “Stick with me and we'll go places.”",
  "How do you stop a bull from charging? Take away its credit card.",
  "What did the ocean say to the beach? Nothing. It just waved.",
  "Why did the boy throw a stick of margarine out the window? He wanted to see a butterfly.",
  "Why doesn't anyone play poker in the jungle? Too many cheetahs.",
  "Why can't you trust stairs? They're always up to something.",
  "What kind of sandals do frogs prefer? Open toad.",
  "How do birds learn how to fly? They wing it.",
  "What kind of shoes do bananas wear? Slippers.",
  "What's a mummy's favorite kind of music? Wrap.",
  "I don't like artists. They tend to be sketchy.",
  "Did you hear about the pasta that got locked out of the house? Gnocci.",
  "I once bought a hat for my leg. It was a kneecap.",
  "What's the best way to put a spaceship to sleep? Rocket.",
  "Bacon and eggs walk into a restaurant. The manager says, “Sorry, we don't serve breakfast here.”",
  "What causes dry skin? A towel.",
  "What do you call a bug that can't make a decision? A may-bee.",
  "Why did the deer go to the dentist? It had buck teeth.",
  "Why did the computer get glasses? It wanted to improve its website.",
  "Did you hear about the medieval lamp? It's a knight light.",
  "Where do chefs learn how to make ice cream? At sundae school.",
  "What did the Dalmatian say after dinner? That hit the spot.",
  "Where do elephants store their clothes? In a trunk.",
  "What did the lawyer wear to court? A law suit.",
  "Why did the Oreo go to the dentist? It lost its filling.",
  "How do you identify a dogwood tree? By its bark.",
  "How do celebrities stay cool? They have a lot of fans.",
  "What's the best way to watch a fishing show? Live stream.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Did you hear about the dull pencil? It was pointless.",
  "What do you call spaghetti in disguise? An impasta.",
  "Why did the police arrest the turkey? They suspected foul play.",
  "What do you call a cold dog? A chili dog.",
  "Why did the tomato blush? It saw the salad dressing.",
  "Did you hear about the emotional wedding? Even the cake was in tiers.",
  "What kind of tree fits in your hand? A palm tree.",
  "What did one hat say to the other? You go on ahead.",
  "How much do roofs cost? Nothing. They're on the house!",
  "What do you call a can opener that doesn't work? A can't opener.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "Why shouldn't you trust atoms? They make up everything.",
  "What did one plate say to the other? Dinner's on me.",
  "What kind of bug can tell time? A clock roach.",
  "Knock, knock! Who's there? The interrupting cow. The interrupting ... MOOOOOOO.",
  "Knock, knock! Who's there? Spell. Spell who? W-H-O.",
  "Knock, knock! Who’s there? Accordion. Accordion who? Accordion my sources, it’s going to rain.",
  "Knock, knock! Who’s there? Ash. Ash who? Gesundheit! Need a tissue?",
  "Knock, knock! Who’s there? Frank. Frank who? Frank you for asking, it’s me.",
  "Knock, knock! Who’s there? Abby. Abby who? Abby just stung me, ouch!",
  "Knock, knock! Who's there? Giraffe. Giraffe who? Giraffe anything to eat? I sure am hungry.",
  "Knock, knock! Who's there? Yvette. Yvette who? Yvette treats animals when they're sick.",
  "Knock, knock! Who's there? Aida. Aida who? Aida big breakfast and now I'm stuffed.",
  "Knock, knock! Who's there? Justin. Justin who? Justin time for dinner.",
  "Knock, knock! Who's there? Olive. Olive who? Olive you.",
  "Knock, knock! Who's there? Teddy. Teddy who? Teddy is my birthday.",
  "Knock, knock! Who's there? Wren. Wren who? Wren will these knock-knock jokes ever end?",
  "Knock, knock! Who's there? Ida. Ida who? Ida know, but you better answer the door.",
  "Knock, knock! Who's there? Cows go. Cows go who? No. Cows go moo.",
  "Knock, knock! Who's there? Needle. Needle who? Needle little help getting in the house.",
  "Where do rabbits go for breakfast? IHOP.",
  "Where do you find a dog with no legs? Right where you left him.",
  "What do call a cold parrot? A brrr-d.",
  "What do you call a fly with no wings? A walk.",
  "What's worse than finding a worm in your apple? Half a worm.",
  "Why did the toilet paper roll down the hill? To get to the bottom.",
  "Why did the photograph go to jail? It was framed.",
  "Why can't your nose be 12 inches long? Because then it would be a foot.",
  "What did one pen say to the other? You're ink-redable.",
  "What do you call a fake father? A faux pa.",
];